Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "agalletS" do |server|
    server.vm.hostname = "agalletS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "agalletS"
      vb.memory = 2048
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "agalletSW" do |worker|
    worker.vm.hostname = "agalletSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "agalletSW"
      vb.memory = 1024
      vb.cpus = 1
    end
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
